#pragma once

#define DEFAULT_STATE_HOST "0.0.0.0"
#define DEFAULT_FUNCTION_CALL_HOST "0.0.0.0"
#define DEFAULT_SNAPSHOT_HOST "0.0.0.0"

#define STATE_ASYNC_PORT 8003
#define STATE_SYNC_PORT 8004
#define STATE_INPROC_LABEL "state"

#define FUNCTION_CALL_ASYNC_PORT 8005
#define FUNCTION_CALL_SYNC_PORT 8006
#define FUNCTION_INPROC_LABEL "function"

#define SNAPSHOT_ASYNC_PORT 8007
#define SNAPSHOT_SYNC_PORT 8008
#define SNAPSHOT_INPROC_LABEL "snapshot"

#define DEFAULT_MPI_BASE_PORT 8800
