// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: faabric
#ifndef GRPC_faabric__INCLUDED
#define GRPC_faabric__INCLUDED

#include "faabric_generated.h"
#include "flatbuffers/grpc.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class SnapshotService final {
 public:
  static constexpr char const* service_full_name() {
    return "SnapshotService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status PushSnapshot(::grpc::ClientContext* context, const flatbuffers::grpc::Message<SnapshotPushRequest>& request, flatbuffers::grpc::Message<SnapshotPushResponse>* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SnapshotPushResponse>>> AsyncPushSnapshot(::grpc::ClientContext* context, const flatbuffers::grpc::Message<SnapshotPushRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SnapshotPushResponse>>>(AsyncPushSnapshotRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SnapshotPushResponse>>> PrepareAsyncPushSnapshot(::grpc::ClientContext* context, const flatbuffers::grpc::Message<SnapshotPushRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SnapshotPushResponse>>>(PrepareAsyncPushSnapshotRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SnapshotPushResponse>>* AsyncPushSnapshotRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<SnapshotPushRequest>& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SnapshotPushResponse>>* PrepareAsyncPushSnapshotRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<SnapshotPushRequest>& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status PushSnapshot(::grpc::ClientContext* context, const flatbuffers::grpc::Message<SnapshotPushRequest>& request, flatbuffers::grpc::Message<SnapshotPushResponse>* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SnapshotPushResponse>>> AsyncPushSnapshot(::grpc::ClientContext* context, const flatbuffers::grpc::Message<SnapshotPushRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SnapshotPushResponse>>>(AsyncPushSnapshotRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SnapshotPushResponse>>> PrepareAsyncPushSnapshot(::grpc::ClientContext* context, const flatbuffers::grpc::Message<SnapshotPushRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SnapshotPushResponse>>>(PrepareAsyncPushSnapshotRaw(context, request, cq));
    }
  
   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SnapshotPushResponse>>* AsyncPushSnapshotRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<SnapshotPushRequest>& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SnapshotPushResponse>>* PrepareAsyncPushSnapshotRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<SnapshotPushRequest>& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PushSnapshot_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
  
  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PushSnapshot(::grpc::ServerContext* context, const flatbuffers::grpc::Message<SnapshotPushRequest>* request, flatbuffers::grpc::Message<SnapshotPushResponse>* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PushSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_PushSnapshot() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PushSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushSnapshot(::grpc::ServerContext* context, const flatbuffers::grpc::Message<SnapshotPushRequest>* request, flatbuffers::grpc::Message<SnapshotPushResponse>* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushSnapshot(::grpc::ServerContext* context, flatbuffers::grpc::Message<SnapshotPushRequest>* request, ::grpc::ServerAsyncResponseWriter< flatbuffers::grpc::Message<SnapshotPushResponse>>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef   WithAsyncMethod_PushSnapshot<  Service   >   AsyncService;
  template <class BaseClass>
  class WithGenericMethod_PushSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_PushSnapshot() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PushSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushSnapshot(::grpc::ServerContext* context, const flatbuffers::grpc::Message<SnapshotPushRequest>* request, flatbuffers::grpc::Message<SnapshotPushResponse>* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PushSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_PushSnapshot() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< flatbuffers::grpc::Message<SnapshotPushRequest>, flatbuffers::grpc::Message<SnapshotPushResponse>>(std::bind(&WithStreamedUnaryMethod_PushSnapshot<BaseClass>::StreamedPushSnapshot, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_PushSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PushSnapshot(::grpc::ServerContext* context, const flatbuffers::grpc::Message<SnapshotPushRequest>* request, flatbuffers::grpc::Message<SnapshotPushResponse>* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPushSnapshot(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< flatbuffers::grpc::Message<SnapshotPushRequest>,flatbuffers::grpc::Message<SnapshotPushResponse>>* server_unary_streamer) = 0;
  };
  typedef   WithStreamedUnaryMethod_PushSnapshot<  Service   >   StreamedUnaryService;
  typedef   Service   SplitStreamedService;
  typedef   WithStreamedUnaryMethod_PushSnapshot<  Service   >   StreamedService;
};


#endif  // GRPC_faabric__INCLUDED
